name: chat-service
version: 1.0.0
repository: chat-service
environment: 'development'
commit_hash: d1daf169f08647c35ffc13e9da612f57cfefa54f
build_date: 'Sun August  22 14:24:43 MDT 2021'
build_epoch_sec: '1504470283'